server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres
    hikari:
      schema: contacts_schema
environment:
  create: 10

#logging:
#  level:
#    root: debug